export const GET_GOODS_LIST = 'GET_GOODS_LIST';
export const GET_GOODS_COUNT = 'GET_GOODS_COUNT';
export const CHANGE_QUERY_INFO = 'CHANGE_QUERY_INFO';

export const ADD_GOODS_MODAL_VISABLE = 'ADD_GOODS_MODAL_VISABLE';